services:
  auth-db:
    image: 'postgres:16'
    container_name: 'auth_db'
    environment:
      - 'POSTGRES_DB=authdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - 'auth_postgres_data:/var/lib/postgresql/data'

  event-db:
    image: 'postgres:16'
    container_name: 'event_db'
    environment:
      - 'POSTGRES_DB=eventdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5434:5432'
    volumes:
      - 'event_postgres_data:/var/lib/postgresql/data'

  booking-db:
    image: 'postgres:16'
    container_name: 'booking_db'
    environment:
      - 'POSTGRES_DB=bookingdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5433:5432'
    volumes:
      - 'booking_postgres_data:/var/lib/postgresql/data'

volumes:
  auth_postgres_data:
  event_postgres_data:
  booking_postgres_data:
