services:
  postgres:
    image: 'postgres:16'
    container_name: 'ticket_db'
    environment:
      - 'POSTGRES_DB=ticketdb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
volumes:
  postgres_data:
